# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA/my_lenet/project_1/project_1.srcs/sources_1/ip/pool1_data_linebuffer/pool1_data_linebuffer.xci
# IP: The module: 'pool1_data_linebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/my_lenet/project_1/project_1.srcs/sources_1/ip/pool1_data_linebuffer/pool1_data_linebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pool1_data_linebuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA/my_lenet/project_1/project_1.srcs/sources_1/ip/pool1_data_linebuffer/pool1_data_linebuffer.xci
# IP: The module: 'pool1_data_linebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/my_lenet/project_1/project_1.srcs/sources_1/ip/pool1_data_linebuffer/pool1_data_linebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pool1_data_linebuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
