# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/DMH/Desktop/project/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/DMH/Desktop/project/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/DMH/Desktop/project/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/DMH/Desktop/project/param/c1_w_1.coe
add_files C:/Users/DMH/Desktop/project/param/c1_w_2.coe
add_files C:/Users/DMH/Desktop/project/param/c1_w_3.coe
add_files C:/Users/DMH/Desktop/project/param/c1_w_4.coe
add_files C:/Users/DMH/Desktop/project/param/c1_w_5.coe
add_files C:/Users/DMH/Desktop/project/param/c1_w_6.coe
add_files C:/Users/DMH/Desktop/project/param/c1_b.coe
add_files c:/Users/DMH/Desktop/project/param/c2_1.coe
add_files c:/Users/DMH/Desktop/project/param/c2_2.coe
add_files c:/Users/DMH/Desktop/project/param/c2_3.coe
add_files c:/Users/DMH/Desktop/project/param/c2_4.coe
add_files c:/Users/DMH/Desktop/project/param/c2_5.coe
read_verilog -library xil_defaultlib {
  C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/new/c2_reshape.v
  C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/new/conv1.v
  C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/new/conv2.v
  C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/new/p1_data_fifo.v
  C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/new/pool1.v
  C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/new/pool2.v
  C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/gray_linebuffer/gray_linebuffer.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/gray_linebuffer/gray_linebuffer_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_1_rom/c1_w_1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_1_rom/c1_w_1_rom_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_3_rom/c1_w_3_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_3_rom/c1_w_3_rom_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_4_rom/c1_w_4_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_4_rom/c1_w_4_rom_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_5_rom/c1_w_5_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_5_rom/c1_w_5_rom_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_6_rom/c1_w_6_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_6_rom/c1_w_6_rom_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_b_rom/c1_b_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_b_rom/c1_b_rom_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_2_rom/c1_w_2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_2_rom/c1_w_2_rom_ooc.xdc]

read_ip -quiet C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/pool1_data_linebuffer/pool1_data_linebuffer.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/pool1_data_linebuffer/pool1_data_linebuffer_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row0/c2_w_row0.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row0/c2_w_row0_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row1/c2_w_row1.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row1/c2_w_row1_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row2/c2_w_row2.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row2/c2_w_row2_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row3/c2_w_row3.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row3/c2_w_row3_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row4/c2_w_row4.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row4/c2_w_row4_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_fifo/c2_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_fifo/c2_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_fifo/c2_fifo_ooc.xdc]

read_ip -quiet c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/p2_linebuffer/p2_linebuffer.xci
set_property used_in_implementation false [get_files -all c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/p2_linebuffer/p2_linebuffer_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
