# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row0/c2_w_row0.xci
# IP: The module: 'c2_w_row0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row0/c2_w_row0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2_w_row0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row0/c2_w_row0.xci
# IP: The module: 'c2_w_row0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c2_w_row0/c2_w_row0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2_w_row0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
