# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/axi_full_0/axi_full_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_full_0 || ORIG_REF_NAME==axi_full_0} -quiet] -quiet
