webtalk_init -webtalk_dir F:/Desktop/AXI_SLAVE/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_AXI_SLAVE_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb  8 21:55:34 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f118c463-0650-4e5f-bc93-d1dbe67f9e6a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "28d402ca8cfa4c83bde05ad7c9490be5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600 6-Core Processor              " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3493 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3208310 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14684_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2584443008 -regid "" -xml F:/Desktop/AXI_SLAVE/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_AXI_SLAVE_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Desktop/AXI_SLAVE/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_AXI_SLAVE_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Desktop/AXI_SLAVE/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/sim_AXI_SLAVE_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
