set_property PACKAGE_PIN P20  [get_ports spi_miso      ]
set_property PACKAGE_PIN R19  [get_ports spi_cs      ]
set_property PACKAGE_PIN J19  [get_ports spi_mosi      ]
set_property PACKAGE_PIN K19  [get_ports spi_sclk      ] 
set_property PACKAGE_PIN U20  [get_ports cmos_rst    ]

set_property PACKAGE_PIN U18  [get_ports rgbin_clk ]
set_property PACKAGE_PIN W16  [get_ports bayer[0]]
set_property PACKAGE_PIN V15  [get_ports bayer[1]]
set_property PACKAGE_PIN Y19  [get_ports bayer[2]]
set_property PACKAGE_PIN Y18  [get_ports bayer[3]]
set_property PACKAGE_PIN V16  [get_ports bayer[4]]
set_property PACKAGE_PIN U17	[get_ports bayta[5]]
set_property PACKAGE_PIN W20  [get_ports bayer[6]]
set_property PACKAGE_PIN T17  [get_ports bayer[7]]

set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_rst]

set_property IOSTANDARD LVCMOS33 [get_ports rgbin_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {bayer[*]}]