######################################################################
#
# File name : conv1_tb_simulate.do
# Created on: Wed May 24 18:57:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.conv1_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {conv1_tb_wave.do}

view wave
view structure
view signals

do {conv1_tb.udo}

run 1000ns
