######################################################################
#
# File name : conv1_tb_wave.do
# Created on: Sun May 14 16:14:31 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
