######################################################################
#
# File name : conv1_tb_compile.do
# Created on: Wed May 24 18:57:58 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../project_1.srcs/sources_1/ip/gray_linebuffer/sim/gray_linebuffer.v" \
"../../../../project_1.srcs/sources_1/ip/c1_w_6_rom/sim/c1_w_6_rom.v" \
"../../../../project_1.srcs/sources_1/ip/c1_w_5_rom/sim/c1_w_5_rom.v" \
"../../../../project_1.srcs/sources_1/ip/c1_w_4_rom/sim/c1_w_4_rom.v" \
"../../../../project_1.srcs/sources_1/ip/c1_w_3_rom/sim/c1_w_3_rom.v" \
"../../../../project_1.srcs/sources_1/ip/c1_w_2_rom/sim/c1_w_2_rom.v" \
"../../../../project_1.srcs/sources_1/ip/c1_w_1_rom/sim/c1_w_1_rom.v" \
"../../../../project_1.srcs/sources_1/ip/c1_b_rom/sim/c1_b_rom.v" \
"../../../../project_1.srcs/sources_1/new/conv1.v" \
"../../../../project_1.srcs/sources_1/new/top.v" \
"../../../../project_1.srcs/sim_1/new/conv1_tb.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

