# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_1_rom/c1_w_1_rom.xci
# IP: The module: 'c1_w_1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_1_rom/c1_w_1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c1_w_1_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_1_rom/c1_w_1_rom.xci
# IP: The module: 'c1_w_1_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/c1_w_1_rom/c1_w_1_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c1_w_1_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
