# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer.xci
# IP: The module: 'conv2_linebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv2_linebuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer.xci
# IP: The module: 'conv2_linebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DMH/Desktop/project/project_1.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv2_linebuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
